name: .NET

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Build and run tests
      run: scripts\run-tests.cmd
      shell: cmd
